name: myproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ğŸ§© UI à¹à¸¥à¸°à¸Ÿà¸­à¸™à¸•à¹Œ
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0

  # ğŸ§© à¸ˆà¸±à¸”à¸à¸²à¸£à¸„à¹ˆà¸² local storage (session/token)
  shared_preferences: ^2.5.3

  # ğŸ§© à¸ªà¸³à¸«à¸£à¸±à¸šà¹€à¸£à¸µà¸¢à¸ API à¹€à¸Šà¹ˆà¸™ logout.php
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/email.png
    - assets/lock.png
    - assets/satellite.png
    - assets/floor1.png
    - assets/floor2.png
    - assets/floor3.png
    - assets/floor4.png
    - assets/floor6.png
    - assets/floor8.png
    - assets/floor9.png
    - assets/floor10.png
    - assets/engineer.png

